// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Throughput.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Throughput_h__
#define __Throughput_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/IncomingAsync.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Demo
{

class Throughput;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Demo::Throughput>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Demo::Throughput*);

}

}

namespace Demo
{

class Throughput;
bool operator==(const Throughput&, const Throughput&);
bool operator<(const Throughput&, const Throughput&);
::Ice::Object* upCast(::Demo::Throughput*);
typedef ::IceInternal::Handle< ::Demo::Throughput> ThroughputPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Demo::Throughput> ThroughputPrx;
void __patch(ThroughputPtr&, const ::Ice::ObjectPtr&);

}

namespace Demo
{

typedef ::std::vector< ::Ice::Byte> ByteSeq;

const ::Ice::Int ByteSeqSize = 500000;

typedef ::std::vector< ::std::string> StringSeq;

const ::Ice::Int StringSeqSize = 50000;

struct StringDouble
{
    ::std::string s;
    ::Ice::Double d;
};

typedef ::std::vector< ::Demo::StringDouble> StringDoubleSeq;

const ::Ice::Int StringDoubleSeqSize = 50000;

struct Fixed
{
    ::Ice::Int i;
    ::Ice::Int j;
    ::Ice::Double d;
};

typedef ::std::vector< ::Demo::Fixed> FixedSeq;

const ::Ice::Int FixedSeqSize = 50000;

}

namespace Ice
{
template<>
struct StreamableTraits< ::Demo::StringDouble>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 9;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Demo::StringDouble, S>
{
    static void write(S* __os, const ::Demo::StringDouble& v)
    {
        __os->write(v.s);
        __os->write(v.d);
    }
};

template<class S>
struct StreamReader< ::Demo::StringDouble, S>
{
    static void read(S* __is, ::Demo::StringDouble& v)
    {
        __is->read(v.s);
        __is->read(v.d);
    }
};

template<>
struct StreamableTraits< ::Demo::Fixed>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 16;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::Demo::Fixed, S>
{
    static void write(S* __os, const ::Demo::Fixed& v)
    {
        __os->write(v.i);
        __os->write(v.j);
        __os->write(v.d);
    }
};

template<class S>
struct StreamReader< ::Demo::Fixed, S>
{
    static void read(S* __is, ::Demo::Fixed& v)
    {
        __is->read(v.i);
        __is->read(v.j);
        __is->read(v.d);
    }
};

}

namespace Demo
{

class AMD_Throughput_echoByteSeq : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&) = 0;
};

typedef ::IceUtil::Handle< ::Demo::AMD_Throughput_echoByteSeq> AMD_Throughput_echoByteSeqPtr;

}

namespace IceAsync
{

namespace Demo
{

class AMD_Throughput_echoByteSeq : public ::Demo::AMD_Throughput_echoByteSeq, public ::IceInternal::IncomingAsync
{
public:

    AMD_Throughput_echoByteSeq(::IceInternal::Incoming&);

    virtual void ice_response(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&);
};

}

}

namespace Demo
{

class Callback_Throughput_echoByteSeq_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Throughput_echoByteSeq_Base> Callback_Throughput_echoByteSeqPtr;

class Callback_Throughput_echoStringSeq_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Throughput_echoStringSeq_Base> Callback_Throughput_echoStringSeqPtr;

class Callback_Throughput_echoStructSeq_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Throughput_echoStructSeq_Base> Callback_Throughput_echoStructSeqPtr;

class Callback_Throughput_echoFixedSeq_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Throughput_echoFixedSeq_Base> Callback_Throughput_echoFixedSeqPtr;

class Callback_Throughput_shutdown_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Throughput_shutdown_Base> Callback_Throughput_shutdownPtr;

}

namespace IceProxy
{

namespace Demo
{

class Throughput : virtual public ::IceProxy::Ice::Object
{
public:

    ::Demo::ByteSeq echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq)
    {
        return echoByteSeq(seq, 0);
    }
    ::Demo::ByteSeq echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context& __ctx)
    {
        return echoByteSeq(seq, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::IceInternal::Function<void (const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoByteSeq(seq, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoByteSeq(seq, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoByteSeq(seq, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoByteSeq(seq, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
                ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> __ret;
                try
                {
                    __proxy->___end_echoByteSeq(__ret, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&)> _response;
        };
        return begin_echoByteSeq(seq, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq)
    {
        return begin_echoByteSeq(seq, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context& __ctx)
    {
        return begin_echoByteSeq(seq, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoByteSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoByteSeq(seq, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Demo::Callback_Throughput_echoByteSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoByteSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& seq, const ::Ice::Context& __ctx, const ::Demo::Callback_Throughput_echoByteSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoByteSeq(seq, &__ctx, __del, __cookie);
    }

    ::Demo::ByteSeq end_echoByteSeq(const ::Ice::AsyncResultPtr&);

     void ___end_echoByteSeq(::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& __ret, const ::Ice::AsyncResultPtr&);
    
private:

    ::Demo::ByteSeq echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq& seq)
    {
        return echoStringSeq(seq, 0);
    }
    ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context& __ctx)
    {
        return echoStringSeq(seq, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::IceInternal::Function<void (const ::Demo::StringSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoStringSeq(seq, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoStringSeq(seq, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Demo::StringSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoStringSeq(seq, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoStringSeq(seq, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Demo::StringSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Demo::StringSeq&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
                ::Demo::StringSeq __ret;
                try
                {
                    __ret = __proxy->end_echoStringSeq(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Demo::StringSeq&)> _response;
        };
        return begin_echoStringSeq(seq, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq& seq)
    {
        return begin_echoStringSeq(seq, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context& __ctx)
    {
        return begin_echoStringSeq(seq, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStringSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStringSeq(seq, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Demo::Callback_Throughput_echoStringSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStringSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq& seq, const ::Ice::Context& __ctx, const ::Demo::Callback_Throughput_echoStringSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStringSeq(seq, &__ctx, __del, __cookie);
    }

    ::Demo::StringSeq end_echoStringSeq(const ::Ice::AsyncResultPtr&);
    
private:

    ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_echoStringSeq(const ::Demo::StringSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq& seq)
    {
        return echoStructSeq(seq, 0);
    }
    ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context& __ctx)
    {
        return echoStructSeq(seq, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::IceInternal::Function<void (const ::Demo::StringDoubleSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoStructSeq(seq, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoStructSeq(seq, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Demo::StringDoubleSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoStructSeq(seq, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoStructSeq(seq, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Demo::StringDoubleSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Demo::StringDoubleSeq&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
                ::Demo::StringDoubleSeq __ret;
                try
                {
                    __ret = __proxy->end_echoStructSeq(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Demo::StringDoubleSeq&)> _response;
        };
        return begin_echoStructSeq(seq, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq)
    {
        return begin_echoStructSeq(seq, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context& __ctx)
    {
        return begin_echoStructSeq(seq, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStructSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStructSeq(seq, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Demo::Callback_Throughput_echoStructSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStructSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq& seq, const ::Ice::Context& __ctx, const ::Demo::Callback_Throughput_echoStructSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoStructSeq(seq, &__ctx, __del, __cookie);
    }

    ::Demo::StringDoubleSeq end_echoStructSeq(const ::Ice::AsyncResultPtr&);
    
private:

    ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_echoStructSeq(const ::Demo::StringDoubleSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq& seq)
    {
        return echoFixedSeq(seq, 0);
    }
    ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context& __ctx)
    {
        return echoFixedSeq(seq, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::IceInternal::Function<void (const ::Demo::FixedSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoFixedSeq(seq, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoFixedSeq(seq, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Demo::FixedSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_echoFixedSeq(seq, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_echoFixedSeq(seq, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Demo::FixedSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Demo::FixedSeq&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
                ::Demo::FixedSeq __ret;
                try
                {
                    __ret = __proxy->end_echoFixedSeq(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Demo::FixedSeq&)> _response;
        };
        return begin_echoFixedSeq(seq, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq& seq)
    {
        return begin_echoFixedSeq(seq, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context& __ctx)
    {
        return begin_echoFixedSeq(seq, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoFixedSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoFixedSeq(seq, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Demo::Callback_Throughput_echoFixedSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoFixedSeq(seq, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq& seq, const ::Ice::Context& __ctx, const ::Demo::Callback_Throughput_echoFixedSeqPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_echoFixedSeq(seq, &__ctx, __del, __cookie);
    }

    ::Demo::FixedSeq end_echoFixedSeq(const ::Ice::AsyncResultPtr&);
    
private:

    ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_echoFixedSeq(const ::Demo::FixedSeq&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void shutdown()
    {
        shutdown(0);
    }
    void shutdown(const ::Ice::Context& __ctx)
    {
        shutdown(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_shutdown(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_shutdown(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_shutdown(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_shutdown(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_shutdown(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_shutdown()
    {
        return begin_shutdown(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx)
    {
        return begin_shutdown(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Demo::Callback_Throughput_shutdownPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context& __ctx, const ::Demo::Callback_Throughput_shutdownPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_shutdown(&__ctx, __del, __cookie);
    }

    void end_shutdown(const ::Ice::AsyncResultPtr&);
    
private:

    void shutdown(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_shutdown(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Throughput> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_secure(bool __secure) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_twoway() const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_oneway() const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_batchOneway() const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_datagram() const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_batchDatagram() const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_compress(bool __compress) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Throughput> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Throughput*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Demo
{

class Throughput : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Demo::ByteSeq echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void shutdown(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Demo
{

class Throughput : virtual public ::IceDelegate::Demo::Throughput,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Demo::ByteSeq echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void shutdown(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Demo
{

class Throughput : virtual public ::IceDelegate::Demo::Throughput,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Demo::ByteSeq echoByteSeq(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void shutdown(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Demo
{

class Throughput : virtual public ::Ice::Object
{
public:

    typedef ThroughputPrx ProxyType;
    typedef ThroughputPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void echoByteSeq_async(const ::Demo::AMD_Throughput_echoByteSeqPtr&, const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___echoByteSeq(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Demo::StringSeq echoStringSeq(const ::Demo::StringSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___echoStringSeq(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Demo::StringDoubleSeq echoStructSeq(const ::Demo::StringDoubleSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___echoStructSeq(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Demo::FixedSeq echoFixedSeq(const ::Demo::FixedSeq&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___echoFixedSeq(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void shutdown(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___shutdown(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Throughput& l, const Throughput& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Throughput& l, const Throughput& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Demo
{

template<class T>
class CallbackNC_Throughput_echoByteSeq : public Callback_Throughput_echoByteSeq_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&);

    CallbackNC_Throughput_echoByteSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> __ret;
        try
        {
            __proxy->___end_echoByteSeq(__ret, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Throughput_echoByteSeqPtr
newCallback_Throughput_echoByteSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoByteSeq<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Throughput_echoByteSeqPtr
newCallback_Throughput_echoByteSeq(T* instance, void (T::*cb)(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoByteSeq<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Throughput_echoByteSeq : public Callback_Throughput_echoByteSeq_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const CT&);

    Callback_Throughput_echoByteSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> __ret;
        try
        {
            __proxy->___end_echoByteSeq(__ret, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Throughput_echoByteSeqPtr
newCallback_Throughput_echoByteSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoByteSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_echoByteSeqPtr
newCallback_Throughput_echoByteSeq(T* instance, void (T::*cb)(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoByteSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Throughput_echoStringSeq : public Callback_Throughput_echoStringSeq_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Demo::StringSeq&);

    CallbackNC_Throughput_echoStringSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::Demo::StringSeq __ret;
        try
        {
            __ret = __proxy->end_echoStringSeq(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Throughput_echoStringSeqPtr
newCallback_Throughput_echoStringSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::StringSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoStringSeq<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Throughput_echoStringSeqPtr
newCallback_Throughput_echoStringSeq(T* instance, void (T::*cb)(const ::Demo::StringSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoStringSeq<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Throughput_echoStringSeq : public Callback_Throughput_echoStringSeq_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Demo::StringSeq&, const CT&);

    Callback_Throughput_echoStringSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::Demo::StringSeq __ret;
        try
        {
            __ret = __proxy->end_echoStringSeq(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Throughput_echoStringSeqPtr
newCallback_Throughput_echoStringSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::StringSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoStringSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_echoStringSeqPtr
newCallback_Throughput_echoStringSeq(T* instance, void (T::*cb)(const ::Demo::StringSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoStringSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Throughput_echoStructSeq : public Callback_Throughput_echoStructSeq_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Demo::StringDoubleSeq&);

    CallbackNC_Throughput_echoStructSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::Demo::StringDoubleSeq __ret;
        try
        {
            __ret = __proxy->end_echoStructSeq(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Throughput_echoStructSeqPtr
newCallback_Throughput_echoStructSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::StringDoubleSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoStructSeq<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Throughput_echoStructSeqPtr
newCallback_Throughput_echoStructSeq(T* instance, void (T::*cb)(const ::Demo::StringDoubleSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoStructSeq<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Throughput_echoStructSeq : public Callback_Throughput_echoStructSeq_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Demo::StringDoubleSeq&, const CT&);

    Callback_Throughput_echoStructSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::Demo::StringDoubleSeq __ret;
        try
        {
            __ret = __proxy->end_echoStructSeq(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Throughput_echoStructSeqPtr
newCallback_Throughput_echoStructSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::StringDoubleSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoStructSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_echoStructSeqPtr
newCallback_Throughput_echoStructSeq(T* instance, void (T::*cb)(const ::Demo::StringDoubleSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoStructSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Throughput_echoFixedSeq : public Callback_Throughput_echoFixedSeq_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Demo::FixedSeq&);

    CallbackNC_Throughput_echoFixedSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::Demo::FixedSeq __ret;
        try
        {
            __ret = __proxy->end_echoFixedSeq(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Throughput_echoFixedSeqPtr
newCallback_Throughput_echoFixedSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::FixedSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoFixedSeq<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Throughput_echoFixedSeqPtr
newCallback_Throughput_echoFixedSeq(T* instance, void (T::*cb)(const ::Demo::FixedSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_echoFixedSeq<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Throughput_echoFixedSeq : public Callback_Throughput_echoFixedSeq_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Demo::FixedSeq&, const CT&);

    Callback_Throughput_echoFixedSeq(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::ThroughputPrx __proxy = ::Demo::ThroughputPrx::uncheckedCast(__result->getProxy());
        ::Demo::FixedSeq __ret;
        try
        {
            __ret = __proxy->end_echoFixedSeq(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Throughput_echoFixedSeqPtr
newCallback_Throughput_echoFixedSeq(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Demo::FixedSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoFixedSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_echoFixedSeqPtr
newCallback_Throughput_echoFixedSeq(T* instance, void (T::*cb)(const ::Demo::FixedSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_echoFixedSeq<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Throughput_shutdown : public Callback_Throughput_shutdown_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Throughput_shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_shutdown<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_shutdown<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_shutdown<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Throughput_shutdown<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Throughput_shutdown : public Callback_Throughput_shutdown_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Throughput_shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_shutdown<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_shutdown<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_shutdown<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Throughput_shutdownPtr
newCallback_Throughput_shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Throughput_shutdown<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
